apiVersion: batch/v1
kind: Job
metadata:
  name: label-pods
  labels:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: kubectl
          image: bitnami/kubectl
          command: ["/bin/sh", "-c"]
          args:
            - kubectl label pods --overwrite -n default --dry-run=client -l "app=demo" "seth=things"
      restartPolicy: Never


